/**
 * src/core/engine.ts
 *
 * Single source of truth for URL context extraction and allow/block decisions.
 * All callers (background, content script, popup) MUST use these functions.
 * Never re-implement URL parsing or allow/block logic elsewhere.
 */

import type { Whitelist, WhitelistItem, Settings, Mode, OverrideState } from '@/storage/types';

// ─── Types (migrated from deleted decision/ folder) ──────────────────────────

export type Action = 'allow' | 'block' | 'override_required';

export interface Verdict {
  action: Action;
  reason: string;
  /**
   * Which check produced this verdict. Shown on block page UI and logged to console.
   */
  source: 'disabled' | 'override' | 'whitelist' | 'default' | 'error';
  signals?: string[];
}

export interface Context {
  /** YouTube video ID from ?v= param, /shorts/ID path, or youtu.be/ID. Null if not found. */
  videoId: string | null;
  /**
   * YouTube playlist ID from ?list= param.
   * Auto-generated mixes (RD*, WL, LL, FL) are stripped here — always null for those.
   * Callers must NOT add isAutoGeneratedPlaylist() checks elsewhere.
   */
  playlistId: string | null;
  /**
   * YouTube channel identifier — either a "UC…" UCID or a "@handle" string.
   * Stored with "@" prefix for handles. Null if not found.
   */
  channelId: string | null;
  /** True when the URL is a YouTube Shorts URL (/shorts/…). */
  isShort: boolean;
  /** Original URL string, preserved for logging and downstream use. */
  url: string;
}

export interface DecisionInput {
  ctx: Context;
  whitelist: Whitelist;
  settings: Settings;
  override: OverrideState;
  mode: Mode;
  now: number;
}

// ─── URL parsing ──────────────────────────────────────────────────────────────

const CHANNEL_UCID_RE = /\/channel\/(UC[a-zA-Z0-9_-]+)/;
const CHANNEL_HANDLE_RE = /\/@([a-zA-Z0-9_.-]+)/;
const YOUTU_BE_HOSTS = new Set(['youtu.be', 'www.youtu.be']);

/**
 * Returns true for YouTube auto-generated mix/radio/system playlist IDs.
 * - RD* — mixes derived from a seed video (My Mix, Song Radio, etc.)
 * - WL  — Watch Later (system playlist, not user-curated for sharing)
 * - LL  — Liked videos
 * - FL  — Favourites (legacy)
 *
 * Stripped inside extractContext so callers never see a poisonous playlist ID.
 * Do NOT duplicate this logic anywhere else in the codebase.
 */
function isAutoGeneratedPlaylist(id: string): boolean {
  return /^RD/i.test(id) || /^(WL|LL|FL)$/.test(id);
}

/**
 * Canonical YouTube URL parser — the single source of truth.
 *
 * Handles:
 *   youtube.com/watch?v=ID
 *   youtube.com/shorts/ID
 *   youtube.com/playlist?list=ID
 *   youtube.com/channel/UCxxx  |  youtube.com/@handle
 *   youtu.be/ID                |  youtu.be/ID?list=PLxxx
 *
 * Auto-generated playlists (RD*, WL, LL, FL) are stripped — ctx.playlistId
 * will be null for them. This prevents a whitelisted seed video from
 * accidentally granting access to its entire auto-generated mix.
 */
export function extractContext(url: string): Context {
  let u: URL;
  try {
    u = new URL(url);
  } catch {
    return { videoId: null, playlistId: null, channelId: null, isShort: false, url };
  }

  const host = u.hostname.toLowerCase();
  const pathname = u.pathname;
  const params = u.searchParams;

  // ── youtu.be/<videoId>[?list=...] ─────────────────────────────────────────
  if (YOUTU_BE_HOSTS.has(host)) {
    // First non-empty path segment is the video ID.
    // Require ≥6 chars to avoid matching bare "/" paths as video IDs.
    const seg = pathname.split('/').filter(Boolean)[0] ?? null;
    const videoId = seg && /^[A-Za-z0-9_-]{6,}$/.test(seg) ? seg : null;
    const rawList = params.get('list');
    const playlistId = rawList && !isAutoGeneratedPlaylist(rawList) ? rawList : null;
    return { videoId, playlistId, channelId: null, isShort: false, url };
  }

  // ── youtube.com/* ─────────────────────────────────────────────────────────
  const isShort = pathname.startsWith('/shorts/');
  const isEmbed = pathname.startsWith('/embed/');
  const isLive = pathname.startsWith('/live/');
  const isTv = pathname.startsWith('/tv');

  // Video ID
  let videoId: string | null = null;
  if (isShort) {
    videoId = pathname.split('/')[2] ?? null;
  } else if (isEmbed || isLive) {
    // /embed/VIDEO_ID or /live/VIDEO_ID
    const seg = pathname.split('/')[2];
    videoId = seg && /^[A-Za-z0-9_-]{6,}$/.test(seg) ? seg : null;
  } else if (pathname === '/watch' || pathname.startsWith('/watch?')) {
    videoId = params.get('v');
  }

  // Playlist ID — strip auto-generated playlists at the source
  const rawList = params.get('list');
  const playlistId = rawList && !isAutoGeneratedPlaylist(rawList) ? rawList : null;

  // Channel ID — URL only; not derivable from /shorts/ or youtu.be URLs
  let channelId: string | null = null;
  if (!isShort && !isEmbed && !isLive && !isTv) {
    const ucid = CHANNEL_UCID_RE.exec(pathname);
    if (ucid) {
      channelId = ucid[1];
    } else {
      const handle = CHANNEL_HANDLE_RE.exec(pathname);
      if (handle) channelId = `@${handle[1]}`;
    }
  }

  // NOTE: If it's `/tv`, we deliberately leave everything null so the default-deny
  // catches it in Strict Mode (since we can't reliably filter the leanback UI).
  return { videoId, playlistId, channelId, isShort, url };
}

/**
 * Backward-compat shim. Delegates to extractContext.
 * @deprecated Use extractContext(url).videoId directly.
 */
export function extractVideoIdFromUrl(url: string): string | null {
  return extractContext(url).videoId;
}

// ─── Whitelist predicate ──────────────────────────────────────────────────────

/**
 * Pure whitelist predicate — checks videos, then playlists, then channels.
 * Exported for direct unit testing without running the full decision pipeline.
 * Note: playlistId is already null for auto-generated mixes (stripped in extractContext).
 */
export function isWhitelisted(ctx: Context, wl: Whitelist): boolean {
  if (ctx.videoId && wl.videos.some((v) => v.id === ctx.videoId)) return true;
  if (ctx.playlistId && wl.playlists.some((p) => p.id === ctx.playlistId)) return true;
  if (ctx.channelId && wl.channels.some((c) => c.id === ctx.channelId)) return true;
  return false;
}

// ─── Registry Pattern Interfaces ──────────────────────────────────────────────

export type Signal = string;

export interface SignalProducer {
  name: string;
  produce(input: DecisionInput): Promise<Signal[]> | Signal[];
}

export interface Resolver {
  resolve(signals: Signal[], input: DecisionInput): Verdict;
}

// ─── Default Producers ────────────────────────────────────────────────────────
import { KeywordProducer } from '@/decision/producers/keyword';

export const OverrideProducer: SignalProducer = {
  name: 'override',
  produce: (input) => {
    const { override, now } = input;
    if (override.disabled) return ['override:disabled'];
    if (override.activeUntil !== null && now < override.activeUntil) return ['override:active'];
    return [];
  }
};

export const ModeProducer: SignalProducer = {
  name: 'mode',
  produce: (input) => {
    return [`mode:${input.mode}`];
  }
};

export const WhitelistProducer: SignalProducer = {
  name: 'whitelist',
  produce: (input) => {
    const signals: Signal[] = [];
    if (isWhitelisted(input.ctx, input.whitelist)) {
      signals.push('whitelist:match');
    }
    return signals;
  }
};

// ─── Default Resolver ─────────────────────────────────────────────────────────

export const DefaultResolver: Resolver = {
  resolve: (signals, input) => {
    if (signals.includes('override:disabled')) {
      return { action: 'allow', reason: 'Blocking disabled', source: 'disabled', signals };
    }
    if (signals.includes('override:active')) {
      return { action: 'allow', reason: 'Override active', source: 'override', signals };
    }
    
    // Explicit whitelist overrides any block keyword
    if (signals.includes('mode:strict') && signals.includes('whitelist:match')) {
      return { action: 'allow', reason: 'Whitelisted', source: 'whitelist', signals };
    }

    // Keyword block overrides allowed keywords or filtered mode
    const blockKeywordMatch = signals.find(s => s.startsWith('keyword:block:'));
    if (blockKeywordMatch) {
      const kw = blockKeywordMatch.split(':')[2];
      return { action: 'block', reason: `Contains blocked keyword: "${kw}"`, source: 'default', signals };
    }

    // Keyword allow overrides strict mode
    const allowKeywordMatch = signals.find(s => s.startsWith('keyword:allow:'));
    if (allowKeywordMatch) {
      const kw = allowKeywordMatch.split(':')[2];
      return { action: 'allow', reason: `Contains allowed keyword: "${kw}"`, source: 'default', signals };
    }

    if (signals.includes('mode:filtered')) {
      return { action: 'allow', reason: 'Filtered mode', source: 'default', signals };
    }
    return { action: 'block', reason: 'Default deny', source: 'default', signals };
  }
};

// ─── Decision engine ──────────────────────────────────────────────────────────

/**
 * Core decision function — asynchronous, extensible via registry pattern.
 *
 * Runs all producers concurrently, collects signals, and resolves them to a Verdict.
 */
export async function decide(
  input: DecisionInput,
  producers: SignalProducer[] = [OverrideProducer, ModeProducer, WhitelistProducer, KeywordProducer],
  resolver: Resolver = DefaultResolver
): Promise<Verdict> {
  try {
    const signalPromises = producers.map((p) => p.produce(input));
    const nestedSignals = await Promise.all(signalPromises);
    const signals = nestedSignals.flat();

    return resolver.resolve(signals, input);
  } catch (err) {
    console.error('[Lockin] decide() threw:', err);
    return { action: 'block', reason: 'Internal error', source: 'error' };
  }
}

// ─── Filtered mode — tile visibility (content script only) ───────────────────
// These stay separate from the navigation decision. Filtered mode gates DOM
// elements, not navigations. Only content.ts should call these.

function matchesItem(items: WhitelistItem[], id: string): boolean {
  return items.some((item) => item.id === id);
}

/**
 * Filtered mode: whether a DOM tile should remain visible.
 * Shorts are ALWAYS hidden — no whitelist entry can override this.
 */
export function isAllowedFiltered(
  ctx: Context,
  whitelist: Whitelist,
  override?: OverrideState,
  now?: number
): boolean {
  // Shorts: always hidden regardless of override or whitelist
  if (ctx.isShort) return false;

  // Blocking disabled → show all non-Short content
  if (override?.disabled) return true;

  // Temporary unlock active → show all non-Short content
  const t = now ?? Date.now();
  if (override?.activeUntil != null && t < override.activeUntil) return true;

  // Whitelist checks (playlistId already null for auto-generated mixes)
  if (ctx.videoId && matchesItem(whitelist.videos, ctx.videoId)) return true;
  if (ctx.playlistId && matchesItem(whitelist.playlists, ctx.playlistId)) return true;
  if (ctx.channelId && matchesItem(whitelist.channels, ctx.channelId)) return true;

  return false;
}

/**
 * Strict mode whitelist check — videos and playlists ONLY.
 * Channels are intentionally excluded in strict mode: a whitelisted channel
 * does not grant access to its page or any video on it. Users must whitelist
 * individual videos or playlists.
 * @deprecated Use decide() for navigation decisions.
 */
export function isAllowedStrict(ctx: Context, whitelist: Whitelist): boolean {
  if (ctx.videoId && whitelist.videos.some((v) => v.id === ctx.videoId)) return true;
  if (ctx.playlistId && whitelist.playlists.some((p) => p.id === ctx.playlistId)) return true;
  return false;
}

/**
 * Unified entry point used by the content script.
 * @deprecated Use decide() for navigation decisions.
 */
export function isAllowed(
  ctx: Context,
  whitelist: Whitelist,
  mode: Mode,
  override?: OverrideState,
  now?: number
): boolean {
  if (mode === 'strict') return isAllowedStrict(ctx, whitelist);
  return isAllowedFiltered(ctx, whitelist, override, now);
}
