/**
 * src/core/engine.ts
 *
 * Single source of truth for URL context extraction and allow/block decisions.
 * All callers (background, content script, popup) MUST use these functions.
 * Never re-implement URL parsing or allow/block logic elsewhere.
 */

import type { Whitelist, WhitelistItem, Settings, Mode, OverrideState } from '@/storage/types';

// ─── Types (migrated from deleted decision/ folder) ──────────────────────────

export type Action = 'allow' | 'block' | 'override_required';

export interface Verdict {
  action: Action;
  reason: string;
  /**
   * Which check produced this verdict. Logged to console for debugging.
   * TODO(provenance): surface source on block page UI.
   */
  source: 'disabled' | 'override' | 'whitelist' | 'default' | 'error';
}

export interface Context {
  /** YouTube video ID from ?v= param, /shorts/ID path, or youtu.be/ID. Null if not found. */
  videoId: string | null;
  /**
   * YouTube playlist ID from ?list= param.
   * Auto-generated mixes (RD*, WL, LL, FL) are stripped here — always null for those.
   * Callers must NOT add isAutoGeneratedPlaylist() checks elsewhere.
   */
  playlistId: string | null;
  /**
   * YouTube channel identifier — either a "UC…" UCID or a "@handle" string.
   * Stored with "@" prefix for handles. Null if not found.
   */
  channelId: string | null;
  /** True when the URL is a YouTube Shorts URL (/shorts/…). */
  isShort: boolean;
  /** Original URL string, preserved for logging and downstream use. */
  url: string;
}

export interface DecisionInput {
  ctx: Context;
  whitelist: Whitelist;
  settings: Settings;
  override: OverrideState;
  mode: Mode;
  now: number;
}

// ─── URL parsing ──────────────────────────────────────────────────────────────

const CHANNEL_UCID_RE = /\/channel\/(UC[a-zA-Z0-9_-]+)/;
const CHANNEL_HANDLE_RE = /\/@([a-zA-Z0-9_.-]+)/;
const YOUTU_BE_HOSTS = new Set(['youtu.be', 'www.youtu.be']);

/**
 * Returns true for YouTube auto-generated mix/radio/system playlist IDs.
 * - RD* — mixes derived from a seed video (My Mix, Song Radio, etc.)
 * - WL  — Watch Later (system playlist, not user-curated for sharing)
 * - LL  — Liked videos
 * - FL  — Favourites (legacy)
 *
 * Stripped inside extractContext so callers never see a poisonous playlist ID.
 * Do NOT duplicate this logic anywhere else in the codebase.
 */
function isAutoGeneratedPlaylist(id: string): boolean {
  return /^RD/i.test(id) || /^(WL|LL|FL)$/.test(id);
}

/**
 * Canonical YouTube URL parser — the single source of truth.
 *
 * Handles:
 *   youtube.com/watch?v=ID
 *   youtube.com/shorts/ID
 *   youtube.com/playlist?list=ID
 *   youtube.com/channel/UCxxx  |  youtube.com/@handle
 *   youtu.be/ID                |  youtu.be/ID?list=PLxxx
 *
 * Auto-generated playlists (RD*, WL, LL, FL) are stripped — ctx.playlistId
 * will be null for them. This prevents a whitelisted seed video from
 * accidentally granting access to its entire auto-generated mix.
 */
export function extractContext(url: string): Context {
  let u: URL;
  try {
    u = new URL(url);
  } catch {
    return { videoId: null, playlistId: null, channelId: null, isShort: false, url };
  }

  const host = u.hostname.toLowerCase();
  const pathname = u.pathname;
  const params = u.searchParams;

  // ── youtu.be/<videoId>[?list=...] ─────────────────────────────────────────
  if (YOUTU_BE_HOSTS.has(host)) {
    // First non-empty path segment is the video ID.
    // Require ≥6 chars to avoid matching bare "/" paths as video IDs.
    const seg = pathname.split('/').filter(Boolean)[0] ?? null;
    const videoId = seg && /^[A-Za-z0-9_-]{6,}$/.test(seg) ? seg : null;
    const rawList = params.get('list');
    const playlistId = rawList && !isAutoGeneratedPlaylist(rawList) ? rawList : null;
    return { videoId, playlistId, channelId: null, isShort: false, url };
  }

  // ── youtube.com/* ─────────────────────────────────────────────────────────
  const isShort = pathname.startsWith('/shorts/');

  // Video ID
  let videoId: string | null = null;
  if (isShort) {
    videoId = pathname.split('/')[2] ?? null;
  } else if (pathname === '/watch' || pathname.startsWith('/watch?')) {
    videoId = params.get('v');
  }

  // Playlist ID — strip auto-generated playlists at the source
  const rawList = params.get('list');
  const playlistId = rawList && !isAutoGeneratedPlaylist(rawList) ? rawList : null;

  // Channel ID — URL only; not derivable from /shorts/ or youtu.be URLs
  let channelId: string | null = null;
  if (!isShort) {
    const ucid = CHANNEL_UCID_RE.exec(pathname);
    if (ucid) {
      channelId = ucid[1];
    } else {
      const handle = CHANNEL_HANDLE_RE.exec(pathname);
      if (handle) channelId = `@${handle[1]}`;
    }
  }

  return { videoId, playlistId, channelId, isShort, url };
}

/**
 * Backward-compat shim. Delegates to extractContext.
 * @deprecated Use extractContext(url).videoId directly.
 */
export function extractVideoIdFromUrl(url: string): string | null {
  return extractContext(url).videoId;
}

// ─── Whitelist predicate ──────────────────────────────────────────────────────

/**
 * Pure whitelist predicate — checks videos, then playlists, then channels.
 * Exported for direct unit testing without running the full decision pipeline.
 * Note: playlistId is already null for auto-generated mixes (stripped in extractContext).
 */
export function isWhitelisted(ctx: Context, wl: Whitelist): boolean {
  if (ctx.videoId && wl.videos.some((v) => v.id === ctx.videoId)) return true;
  if (ctx.playlistId && wl.playlists.some((p) => p.id === ctx.playlistId)) return true;
  if (ctx.channelId && wl.channels.some((c) => c.id === ctx.channelId)) return true;
  return false;
}

// ─── Decision engine ──────────────────────────────────────────────────────────

/**
 * Core decision function — synchronous, pure, fail-closed.
 *
 * Takes a pre-built DecisionInput (storage data resolved by the caller) and
 * returns a Verdict synchronously. The async boundary (storage.get) belongs
 * in the interception layer — not here. This keeps the decision logic
 * independently testable without mocking chrome.storage.
 *
 * Order of checks is semantic and intentional:
 *   1. disabled  → always allow (user completed typing challenge)
 *   2. override  → always allow (temp unlock, not yet expired)
 *   3. whitelist → allow if content is explicitly permitted
 *   4. filtered  → allow (DOM filter handles tile visibility separately)
 *   5. default   → block (fail-closed)
 */
export function decide(input: DecisionInput): Verdict {
  try {
    const { ctx, whitelist, override, mode, now } = input;

    // 1. Blocking fully disabled by user
    if (override.disabled) {
      return { action: 'allow', reason: 'Blocking disabled', source: 'disabled' };
    }

    // 2. Temporary unlock — active and not yet expired
    if (override.activeUntil !== null && now < override.activeUntil) {
      return { action: 'allow', reason: 'Override active', source: 'override' };
    }

    // 3. Whitelist check (strict mode only)
    if (mode === 'strict' && isWhitelisted(ctx, whitelist)) {
      return { action: 'allow', reason: 'Whitelisted', source: 'whitelist' };
    }

    // 4. Filtered mode — navigation never blocked; content script gates DOM tiles
    if (mode === 'filtered') {
      return { action: 'allow', reason: 'Filtered mode', source: 'default' };
    }

    // 5. Default deny (fail-closed)
    return { action: 'block', reason: 'Default deny', source: 'default' };
  } catch (err) {
    console.error('[Lockin] decide() threw:', err);
    return { action: 'block', reason: 'Internal error', source: 'error' };
  }
}

// ─── Filtered mode — tile visibility (content script only) ───────────────────
// These stay separate from the navigation decision. Filtered mode gates DOM
// elements, not navigations. Only content.ts should call these.

function matchesItem(items: WhitelistItem[], id: string): boolean {
  return items.some((item) => item.id === id);
}

/**
 * Filtered mode: whether a DOM tile should remain visible.
 * Shorts are ALWAYS hidden — no whitelist entry can override this.
 */
export function isAllowedFiltered(
  ctx: Context,
  whitelist: Whitelist,
  override?: OverrideState,
  now?: number
): boolean {
  // Shorts: always hidden regardless of override or whitelist
  if (ctx.isShort) return false;

  // Blocking disabled → show all non-Short content
  if (override?.disabled) return true;

  // Temporary unlock active → show all non-Short content
  const t = now ?? Date.now();
  if (override?.activeUntil != null && t < override.activeUntil) return true;

  // Whitelist checks (playlistId already null for auto-generated mixes)
  if (ctx.videoId && matchesItem(whitelist.videos, ctx.videoId)) return true;
  if (ctx.playlistId && matchesItem(whitelist.playlists, ctx.playlistId)) return true;
  if (ctx.channelId && matchesItem(whitelist.channels, ctx.channelId)) return true;

  return false;
}

/**
 * Strict mode whitelist check — videos and playlists ONLY.
 * Channels are intentionally excluded in strict mode: a whitelisted channel
 * does not grant access to its page or any video on it. Users must whitelist
 * individual videos or playlists.
 * @deprecated Use decide() for navigation decisions.
 */
export function isAllowedStrict(ctx: Context, whitelist: Whitelist): boolean {
  if (ctx.videoId && whitelist.videos.some((v) => v.id === ctx.videoId)) return true;
  if (ctx.playlistId && whitelist.playlists.some((p) => p.id === ctx.playlistId)) return true;
  return false;
}

/**
 * Unified entry point used by the content script.
 * @deprecated Use decide() for navigation decisions.
 */
export function isAllowed(
  ctx: Context,
  whitelist: Whitelist,
  mode: Mode,
  override?: OverrideState,
  now?: number
): boolean {
  if (mode === 'strict') return isAllowedStrict(ctx, whitelist);
  return isAllowedFiltered(ctx, whitelist, override, now);
}
